/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ReliabilityRouteImport } from './routes/reliability'
import { Route as WhatifRouteImport } from './routes/whatif'
import { Route as CropCropIdRouteImport } from './routes/crop.$cropId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ReliabilityRoute = ReliabilityRouteImport.update({
  id: '/reliability',
  path: '/reliability',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatifRoute = WhatifRouteImport.update({
  id: '/whatif',
  path: '/whatif',
  getParentRoute: () => rootRouteImport,
} as any)
const CropCropIdRoute = CropCropIdRouteImport.update({
  id: '/crop/$cropId',
  path: '/crop/$cropId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/business': typeof BusinessRoute
  '/farmer': typeof FarmerRoute
  '/how-it-works': typeof HowItWorksRoute
  '/recommendations': typeof RecommendationsRoute
  '/reliability': typeof ReliabilityRoute
  '/whatif': typeof WhatifRoute
  '/crop/$cropId': typeof CropCropIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/business': typeof BusinessRoute
  '/farmer': typeof FarmerRoute
  '/how-it-works': typeof HowItWorksRoute
  '/recommendations': typeof RecommendationsRoute
  '/reliability': typeof ReliabilityRoute
  '/whatif': typeof WhatifRoute
  '/crop/$cropId': typeof CropCropIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/business': typeof BusinessRoute
  '/farmer': typeof FarmerRoute
  '/how-it-works': typeof HowItWorksRoute
  '/recommendations': typeof RecommendationsRoute
  '/reliability': typeof ReliabilityRoute
  '/whatif': typeof WhatifRoute
  '/crop/$cropId': typeof CropCropIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/business'
    | '/farmer'
    | '/how-it-works'
    | '/recommendations'
    | '/reliability'
    | '/whatif'
    | '/crop/$cropId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/business'
    | '/farmer'
    | '/how-it-works'
    | '/recommendations'
    | '/reliability'
    | '/whatif'
    | '/crop/$cropId'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/business'
    | '/farmer'
    | '/how-it-works'
    | '/recommendations'
    | '/reliability'
    | '/whatif'
    | '/crop/$cropId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  BusinessRoute: typeof BusinessRoute
  FarmerRoute: typeof FarmerRoute
  HowItWorksRoute: typeof HowItWorksRoute
  RecommendationsRoute: typeof RecommendationsRoute
  ReliabilityRoute: typeof ReliabilityRoute
  WhatifRoute: typeof WhatifRoute
  CropCropIdRoute: typeof CropCropIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reliability': {
      id: '/reliability'
      path: '/reliability'
      fullPath: '/reliability'
      preLoaderRoute: typeof ReliabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatif': {
      id: '/whatif'
      path: '/whatif'
      fullPath: '/whatif'
      preLoaderRoute: typeof WhatifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop/$cropId': {
      id: '/crop/$cropId'
      path: '/crop/$cropId'
      fullPath: '/crop/$cropId'
      preLoaderRoute: typeof CropCropIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  BusinessRoute: BusinessRoute,
  FarmerRoute: FarmerRoute,
  HowItWorksRoute: HowItWorksRoute,
  RecommendationsRoute: RecommendationsRoute,
  ReliabilityRoute: ReliabilityRoute,
  WhatifRoute: WhatifRoute,
  CropCropIdRoute: CropCropIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
